### ISSUE TITLE
 Remplir fiche projet

### ISSUE THREAD

**Issue by L00rdD** [Taishoberius/rised-android#7]
[Fiche.projet.1.docx](https://github.com/Taishoberius/rised-things/files/2984126/Fiche.projet.1.docx)
[Le Vrai Doc](https://docs.google.com/document/d/1mwpwA0rS8E4N6s1w7xZmXgfOteIajHw4AKOEa6Xzl34/edit?usp=drive_web&ouid=103834438859305487441)

**Comment by LinharesDavid** [comment]
[Fiche projet (1).docx](https://github.com/Taishoberius/rised-things/files/2984123/Fiche.projet.1.docx)
